### PR TITLE
LLVM bump next

### PR DESCRIPTION
**Pull request by mgehre-amd**

### CODE REVIEW

**Review by ljfitz — CHANGES_REQUESTED** [review]
I checked with `git difftool -d $(git merge-base HEAD origin/main) HEAD` and saw a couple of things:
- "third_party/pybind11" differs. Unexpected?
- "third_party/rapidcheck" differs.  Unexpected?

Also some NITs where I'm not sure the difference from `main` is of benefit.

Line not in `main` "src/Conversion/ONNXToKrnl/Tensor/Pad.cpp"?
```
15: #include "mlir/IR/BuiltinTypes.h"
```

From line 5 in `main` "src/Conversion/ONNXToTOSA/CMakeLists.txt" (also some other lines in different order):
```
7:   DialectBuilder.cpp
```

It was a useful reminder of:
- how much onnx-to-tosa still need to go upstream (I hadn't looked at https://github.com/ljfitz/onnx-mlir/issues/104 in a while)
- https://github.com/ljfitz/onnx-mlir/pull/128 didn't move out of draft once we removed our dependence on `onnx-to-torch`.

**Review by maxbartel — APPROVED** [review]
ONNX to TOSA part looks alright

**Comment by mgehre-amd** [comment]
After this PR is done and approved, I will push this over to https://github.com/xilinx/onnx-mlir and target `feature/onnx-to-tosa`

**Comment by ttjost** [comment]
> > I checked with `git difftool -d $(git merge-base HEAD origin/main) HEAD` and saw a couple of things:
> > 
> > * "third_party/pybind11" differs. Unexpected?
> > * "third_party/rapidcheck" differs.  Unexpected?
> > 
> > Also some NITs where I'm not sure the difference from `main` is of benefit.
> > Line not in `main` "src/Conversion/ONNXToKrnl/Tensor/Pad.cpp"?
> > ```
> > 15: #include "mlir/IR/BuiltinTypes.h"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From line 5 in `main` "src/Conversion/ONNXToTOSA/CMakeLists.txt" (also some other lines in different order):
> > ```
> > 7:   DialectBuilder.cpp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It was a useful reminder of:
> > 
> > * how much onnx-to-tosa still need to go upstream (I hadn't looked at [ONNX to TOSA Legalization Upstream tracker #104](https://github.com/ljfitz/onnx-mlir/issues/104) in a while)
> > * [remove onnx to torch #128](https://github.com/ljfitz/onnx-mlir/pull/128) didn't move out of draft once we removed our dependence on `onnx-to-torch`.
> 
> @ttjost, for my understanding, did you address any of those comments from Liam in your commits or are they still open?

I didn't see there was any comment. So, they haven't been addressed.

**Review by ljfitz — APPROVED** [review]

**Comment by mgehre-amd** [comment]
Closed in favor of https://github.com/Xilinx/onnx-mlir/pull/5

**Pull request closed without merging**
