### PR TITLE
Remove llvm::outs() debug logs

### PR DESCRIPTION
**Pull request by oowekyala**
Running `onnx-mlir` with the `--debug` includes the same information. For instance, for every pattern application, the source operator is shown, the individual transformations and the result code. For instance: 
```
Legalizing operation : 'onnx.MaxPoolSingleOut'(0x40faa70) {
  %1 = "onnx.MaxPoolSingleOut"(%0) {dilations = [1, 1], group = 1 : si64, kernel_shape = [3, 3], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<20x16x50x40xf32>) -> tensor<20x16x48x38xf32>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'onnx.MaxPoolSingleOut -> ()' {
Trying to match "ONNXMaxPoolSingleOutOpToTorchLowering"
    ** Insert  : 'torch.constant.int'(0x41370e0)
    ** Insert  : 'torch.constant.int'(0x4130e60)
    ...
    ** Insert  : 'torch.aten.max_pool2d'(0x205daf0)
```
and later the result is seen with full operands:
```
    Legalizing operation : 'torch.aten.max_pool2d'(0x205daf0) {
      %16 = "torch.aten.max_pool2d"(%15, %14, %11, %13, %12, %10) : (!torch.vtensor<[20,16,50,40],f32>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool) -> !torch.vtensor<[20,16,48,38],f32>
```

Please let me know if there is a good reason to keep some of them, we can revert this partly

### CODE REVIEW

**Review by ljfitz — APPROVED** [review]
Thanks @oowekyala - this seems to have all the details in `--debug` and it is great to have log output for debugging under the standard mechanism and only on request.

**Review by ayonam-helprack — CHANGES_REQUESTED** [review]
The changes otherwise look fine to me.

There are five files with names that end with TransformToTorchPass.cpp.   I feel we don't  need these files.  Can someone please check this and if we don't need them, then can we please have them removed?

**Comment by oowekyala** [comment]
Indeed those files are not needed. I also removed another file that had been copy pasted from Conversion/OnnxToKrnl without changes

**Comment by vasantha-helprack** [comment]
LGTM

**Review by vasantha-helprack — APPROVED** [review]
LGTM

**Pull request merged**
